//! Embed the cross-compiled `tepegoz-agent` binaries into the
//! controller and enforce protocol-version parity at compile time.
//!
//! Input shape, produced by `cargo xtask build-agents`:
//! ```text
//! target/agents/<triple>/tepegoz-agent      (binary)
//! target/agents/<triple>/manifest.json      ({"protocol_version": N, ...})
//! ```
//!
//! Output: `$OUT_DIR/embedded_agents.rs` — included from `src/agents.rs`
//! — exposes `pub mod embedded_agents { pub const ..., pub fn
//! for_target(triple) -> Option<&'static [u8]> }`.
//!
//! Version-drift defence (load-bearing per the Phase 6 brief): for
//! every populated target, parse its `manifest.json`, assert
//! `protocol_version` matches `tepegoz-proto`'s `PROTOCOL_VERSION`
//! text file. Mismatch is a hard build failure so a stale agent can
//! never masquerade as current. The runtime handshake
//! (`AgentHandshakeResponse.version`) is the second line of defence
//! for user-deployed (non-embedded) agents.
//!
//! Graceful fallback: a missing `target/agents/` tree is a
//! `cargo:warning`, not a failure — plain `cargo build` must not
//! require `cargo xtask build-agents` to have run.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const TARGETS: &[&str] = &[
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is crates/..")
        .to_path_buf();

    // Source of truth — the plain-text PROTOCOL_VERSION file in the
    // proto crate. Read directly rather than through the Rust const
    // because build.rs executes before any crate in the workspace
    // compiles, so we can't depend on the proto lib.
    let proto_version_file = workspace_root
        .join("crates")
        .join("tepegoz-proto")
        .join("PROTOCOL_VERSION");
    println!("cargo:rerun-if-changed={}", proto_version_file.display());
    let proto_version = parse_version(&proto_version_file);

    let agents_root = workspace_root.join("target").join("agents");
    let mut emitted = String::new();
    emitted.push_str(
        "// Generated by crates/tepegoz/build.rs — do not edit.\n\
         //\n\
         // Every target this controller can deploy to gets an entry\n\
         // here. `Some(bytes)` means the agent was cross-compiled by\n\
         // `cargo xtask build-agents` and is embedded; `None` means\n\
         // that target wasn't populated at compile time (plain\n\
         // `cargo build` scenario).\n\n\
         pub mod embedded_agents {\n",
    );

    let mut populated_count = 0usize;
    for triple in TARGETS {
        let const_name = triple_to_const_ident(triple);
        let triple_dir = agents_root.join(triple);
        let bin_path = triple_dir.join("tepegoz-agent");
        let manifest_path = triple_dir.join("manifest.json");

        // Rerun hints — cargo watches these so a fresh `xtask
        // build-agents` re-triggers this build.rs.
        println!("cargo:rerun-if-changed={}", bin_path.display());
        println!("cargo:rerun-if-changed={}", manifest_path.display());

        let bytes_expr = match (bin_path.exists(), manifest_path.exists()) {
            (true, true) => {
                let embedded_version = read_manifest_version(&manifest_path);
                if embedded_version != proto_version {
                    // Hard stop. A stale agent riding on current
                    // protocol would corrupt the handshake + every
                    // downstream subscription; fail loudly rather
                    // than let it slip through.
                    panic!(
                        "tepegoz agent at {} reports protocol v{}, but tepegoz-proto is v{}. \
                         Rebuild agents with `cargo xtask build-agents` (or delete target/agents/ and rebuild).",
                        bin_path.display(),
                        embedded_version,
                        proto_version,
                    );
                }
                populated_count += 1;
                format!("Some(include_bytes!(r\"{}\"))", bin_path.display())
            }
            (true, false) | (false, true) => {
                println!(
                    "cargo:warning=tepegoz-agent/{triple}: found partial artifact (binary or manifest missing). Run `cargo xtask build-agents` to repopulate."
                );
                "None".to_string()
            }
            (false, false) => "None".to_string(),
        };

        emitted.push_str(&format!(
            "    pub const {const_name}: Option<&[u8]> = {bytes_expr};\n"
        ));
    }

    emitted.push_str(
        r#"
    /// Look up the embedded agent binary for a target triple.
    /// Returns `None` when that target wasn't populated via
    /// `cargo xtask build-agents` at compile time.
    #[allow(dead_code)]
    pub fn for_target(triple: &str) -> Option<&'static [u8]> {
        match triple {
            "x86_64-unknown-linux-musl" => X86_64_UNKNOWN_LINUX_MUSL,
            "aarch64-unknown-linux-musl" => AARCH64_UNKNOWN_LINUX_MUSL,
            "x86_64-apple-darwin" => X86_64_APPLE_DARWIN,
            "aarch64-apple-darwin" => AARCH64_APPLE_DARWIN,
            _ => None,
        }
    }
}
"#,
    );

    if populated_count == 0 {
        // Single high-signal warning for the "nobody ran xtask"
        // common case — otherwise four per-target warnings would
        // drown the log. The controller still compiles; remote
        // deploy just fails gracefully at runtime.
        println!(
            "cargo:warning=tepegoz-agent binaries not found at target/agents/. Remote deploy will be unavailable at runtime. Run `cargo xtask build-agents` to populate (requires zig + cargo-zigbuild)."
        );
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let out_path = out_dir.join("embedded_agents.rs");
    fs::write(&out_path, emitted)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
}

fn parse_version(path: &Path) -> u32 {
    let raw = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    raw.trim().parse().unwrap_or_else(|e| {
        panic!(
            "{} must contain a u32 decimal literal, got {:?}: {e}",
            path.display(),
            raw.trim()
        )
    })
}

fn read_manifest_version(path: &Path) -> u32 {
    let raw = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read agent manifest {}: {e}", path.display()));
    let parsed: serde_json::Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("agent manifest {} is not valid JSON: {e}", path.display()));
    parsed
        .get("protocol_version")
        .and_then(|v| v.as_u64())
        .unwrap_or_else(|| {
            panic!(
                "agent manifest {} missing numeric `protocol_version` field",
                path.display()
            )
        }) as u32
}

fn triple_to_const_ident(triple: &str) -> String {
    triple.replace('-', "_").to_uppercase()
}
