//! Embedded agent binaries + the `for_target()` lookup helper.
//!
//! The real contents of this module are generated by
//! `crates/tepegoz/build.rs` and dropped into `$OUT_DIR/
//! embedded_agents.rs`; we just `include!` them here so the rest of
//! the controller can depend on `crate::agents::embedded_agents::…`
//! through a normal module path.
//!
//! Decision #3 puts all four cross-compiled agent binaries inside the
//! controller via `include_bytes!`; the daemon detects the remote
//! target and chooses the right blob at deploy time in Slice 6b.
//! 6a's only consumer is `cargo xtask build-agents` (+ CI's plain
//! `cargo build`, which hits the graceful-fallback path emitting
//! `None` for every target).

// Slice 6a consumers are the xtask demo + (downstream) Slice 6b's
// remote deploy. The per-target consts aren't referenced by the 6a
// code path so we pre-emptively silence dead-code for the module —
// otherwise every plain `cargo build` without populated agents would
// surface four "unused const" warnings.
#[allow(dead_code, unused_imports)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/embedded_agents.rs"));
}

#[allow(unused_imports)]
pub use generated::embedded_agents;
